### ISSUE TITLE
All connect attempts return a 401, works in browser

### ISSUE THREAD

**Issue by jackvalko** [ktelep/EMCUnity#1]
When attempting to access a resource via the python library, all requests return a 401 Unauthorized.  Using the API from a browser works with the same credentials.

Sample code:
```
#!/usr/bin/python
from EMCUnity import *
from pprint import pprint
import requests
import urllib3
import sys

# turn down warnings
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# discover Unity
host = sys.argv[1]
user = "admin"
passwd = "**********"

# connect
unity = Unity(host,user,passwd)
pprint (vars(unity))
pprint (unity.license())
```

Output:

{'api_url': 'https://unity0/api',
 'headers': {'Accept': 'application/json',
             'Content-type': 'application/json',
             'EMC-CSRF-TOKEN': None,
             'X-EMC-REST-CLIENT': 'true'},
 'ip_addr': 'unity0',
 'is_auth': True,
 'model': u'Unity 350F',
 'name': u'unity0',
 'password': '**********',
 'session': <requests.sessions.Session object at 0x10678d0>,
 'software': u'4.2.0',
 'username': 'admin'}
Traceback (most recent call last):
  File "./discover.py", line 20, in <module>
    pprint (unity.license())
  File "/tmp/EMCUnity-master/EMCUnity/Unity.py", line 508, in license
    item_id=item_id, item_name=item_name)
  File "/tmp/EMCUnity-master/EMCUnity/Unity.py", line 133, in get_object
    response = self.get_from_type('/types/%s/instances' % unity_type, unity_object, payload = payload)
  File "/tmp/EMCUnity-master/EMCUnity/Unity.py", line 52, in get_from_type
    response = self.unity_request(url_path,'GET',payload = payload).json()
  File "/tmp/EMCUnity-master/EMCUnity/Unity.py", line 105, in unity_request
    self.process_response(response)
  File "/tmp/EMCUnity-master/EMCUnity/Unity.py", line 32, in process_response
    response.raise_for_status()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 834, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized

Questions:
Does the fact my unity has a self-signed certificate matter?  I suppressed the warning messages, but it occurs to me the library may not accept it.

Thank you.

**Comment by jackvalko** [comment]
It looks like the library assumes that if EMC-CSRF-TOKEN is returned, it contains a token.  If it is NULL, the library thinks it is authorized.  I changed process_response() in unity.py to correctly set the auth flag if the token is not empty:

```
    def process_response(self, response):
        """ Process the HTTPS response and set headers or raise exceptions """
        # TODO: work with Exceptions for easier troubleshooting
        response.raise_for_status()

        if 'EMC-CSRF-TOKEN' not in self.headers:
            self.headers['EMC-CSRF-TOKEN'] = response.headers.get('emc-csrf-token')

        if self.headers['EMC-CSRF-TOKEN']:
            self.is_auth = True

        return

```
